# Generated by Django 3.1.7 on 2021-04-01 20:58

from django.db import migrations, models
import unievents.models


class Migration(migrations.Migration):

    dependencies = [
        ('unievents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='coordinates',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='university',
            name='avatar_image',
            field=models.ImageField(blank=True, db_column='avatar_image', null=True, upload_to=unievents.models.uni_image_upload_to),
        ),
    ]
