# Generated by Django 3.1.7 on 2021-04-02 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unievents', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('longitude', 'latitude')},
        ),
    ]
