# Generated by Django 3.1.7 on 2021-04-02 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unievents', '0002_auto_20210402_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='unievents.location'),
        ),
    ]
