# Generated by Django 3.1.7 on 2021-04-04 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unievents', '0004_auto_20210403_1339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member_of',
        ),
    ]
