# Generated by Django 3.1.7 on 2021-04-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unievents', '0006_auto_20210405_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dtend',
            field=models.DateTimeField(blank=True, db_column='dtend'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dtstart',
            field=models.DateTimeField(blank=True, db_column='dtstart'),
        ),
        migrations.AlterField(
            model_name='event',
            name='freq',
            field=models.TextField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], db_column='freq', null=True, verbose_name='frequency'),
        ),
        migrations.AlterField(
            model_name='event',
            name='privacy_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Public'), (2, 'University Private'), (3, 'Rso Private')], db_column='privacy_level'),
        ),
        migrations.AlterField(
            model_name='event',
            name='until',
            field=models.DateTimeField(db_column='until', null=True),
        ),
    ]
