# Generated by Django 3.1.7 on 2021-04-05 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unievents', '0007_auto_20210405_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rso',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='unievents.rso'),
        ),
    ]
