# Generated by Django 3.1.7 on 2021-04-05 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unievents', '0008_auto_20210405_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_postdate',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.AutoField(db_column='comment_id', default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='postdate',
            field=models.DateTimeField(auto_now_add=True, db_column='postdate', default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='unievents.event'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(blank=True, db_column='rating', default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
