# Generated by Django 3.1.7 on 2021-04-05 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unievents', '0009_auto_20210405_1533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Studies_at',
        ),
    ]
