# Generated by Django 3.1.8 on 2021-04-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unievents', '0010_delete_studies_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='freq',
            field=models.TextField(choices=[('ONCE', 'Once'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], db_column='freq', default='ONCE', null=True, verbose_name='frequency'),
        ),
        migrations.AlterField(
            model_name='event',
            name='privacy_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Public'), (2, 'University Private'), (3, 'Rso Private')], db_column='privacy_level', default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='until',
            field=models.DateField(db_column='until', null=True),
        ),
    ]
