# Generated by Django 3.1.8 on 2021-04-06 20:59

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import unievents.models


class Migration(migrations.Migration):

    dependencies = [
        ('unievents', '0011_auto_20210406_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(db_column='rating'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(db_column='text'),
        ),
        migrations.AlterField(
            model_name='event',
            name='byday',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], db_column='byday', max_length=20, null=True, verbose_name='Repeat on'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, db_column='description', default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='dtstart',
            field=models.DateTimeField(db_column='dtstart'),
        ),
        migrations.AlterField(
            model_name='event',
            name='email',
            field=models.TextField(db_column='email', default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='freq',
            field=models.TextField(blank=True, choices=[('ONCE', 'Once'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], db_column='freq', default='ONCE', verbose_name='frequency'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unievents.location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='phone',
            field=models.TextField(db_column='phone', default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='privacy_level',
            field=models.IntegerField(choices=[(1, 'Public'), (2, 'University Private'), (3, 'Rso Private')], db_column='privacy_level', default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='rso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='unievents.rso'),
        ),
        migrations.AlterField(
            model_name='event',
            name='until',
            field=models.DateField(blank=True, db_column='until', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(db_column='image', upload_to=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(db_column='latitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(db_column='longitude'),
        ),
        migrations.AlterField(
            model_name='rso',
            name='description',
            field=models.TextField(blank=True, db_column='description', default=''),
        ),
        migrations.AlterField(
            model_name='university',
            name='avatar_image',
            field=models.ImageField(db_column='avatar_image', upload_to=unievents.models.uni_image_upload_to),
        ),
        migrations.AlterField(
            model_name='university',
            name='description',
            field=models.TextField(blank=True, db_column='description', default=''),
        ),
        migrations.AlterField(
            model_name='university',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unievents.location'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.TextField(db_column='name'),
        ),
        migrations.AlterField(
            model_name='university',
            name='student_count',
            field=models.IntegerField(blank=True, db_column='student_count'),
        ),
    ]
