# Generated by Django 3.1.8 on 2021-04-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unievents', '0012_auto_20210406_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='freq',
            field=models.TextField(blank=True, choices=[('ONCE', 'Once'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], db_column='freq', default='ONCE', verbose_name='frequency'),
        ),
    ]
