# Generated by Django 3.1.8 on 2021-04-09 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unievents', '0017_event_university'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
    ]
