# Generated by Django 3.1.8 on 2021-04-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unievents', '0019_auto_20210409_0620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='rso',
            old_name='rso_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='university_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(db_column='tag_id', primary_key=True, serialize=False),
        ),
    ]
