# Generated by Django 3.2 on 2021-04-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unievents', '0021_alter_university_student_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='freq',
            field=models.TextField(choices=[('ONCE', 'Once'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], db_column='freq', default='ONCE', verbose_name='frequency'),
        ),
    ]
