# Generated by Django 3.1.7 on 2021-03-31 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsomaker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventid',
            new_name='event_id',
        ),
        migrations.RenameField(
            model_name='event_tag',
            old_name='event_tagid',
            new_name='event_tag_id',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='google_placeid',
            new_name='google_place_id',
        ),
        migrations.RenameField(
            model_name='rso',
            old_name='rsoid',
            new_name='rso_id',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='universityid',
            new_name='university_id',
        ),
    ]
