# Generated by Django 3.1.7 on 2021-03-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsomaker', '0002_auto_20210331_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.AutoField(db_column='event_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event_tag',
            name='event_tag_id',
            field=models.AutoField(db_column='event_tag_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='google_place_id',
            field=models.AutoField(db_column='google_place_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rso',
            name='rso_id',
            field=models.AutoField(db_column='rso_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_id',
            field=models.AutoField(db_column='university_id', primary_key=True, serialize=False),
        ),
    ]
